version: "3.8"

services:
  sb-app:
    image: drugman21/student:latest
    build: .
    container_name: "java-app"
    ports:
      - 9090:9090
    networks:
      - mynetwork
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - "27070:27017"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
