apiVersion: v1
kind: Service
metadata:
  labels:
    app: studentdb
  name: studentdb-service
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: studentdb
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: studentdb
  labels:
    app: studentdb
spec:
  selector:
    matchLabels:
      app: studentdb
  replicas: 1
  template:
    metadata:
      labels:
        app: studentdb
      name: studentdb-service

    spec:
      containers:
      - image: mongo:latest
        name: studentdb
        ports:
        - containerPort: 27017
          name: studentdb
